get http://localhost:3001/api/persons
###
get http://localhost:3001/info
###
get http://localhost:3001/api/persons/23
###
get http://localhost:3001/api/persons/2
###
delete http://localhost:3001/api/persons/2
###
post http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "vatsal",
    "number": "9712930871"
}
###
post http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "9712930871"
}